Usage of buy pack function
EnabApp/core pull request #19
Opened 2022-09-06 18:49 UTC by MohammedJ18

2022-09-06 19:58 UTC, Gruce requested changes
Hello @MohammedJ18 ,

Please specify the error message in `useAppManager` and return them.

Thank you.

2022-09-07 10:34 UTC, MohammedJ18 commented
Hello @Gruce,

I have finished specifying the error message in `useAppManager `.
Thank you.

2022-09-07 13:28 UTC, Gruce requested changes

2022-09-07 13:28 UTC, Gruce commented on src/runtime/composables/useAppManager.ts
> +            if (error)console.log('حدث خطأ اثناء شراء الباقة')
This should not write the error in the console. Because it will not be useful.
When call `buyPack(pack_id)` it should return the specific error in return.
For example:
```ts
if (error) { 
   switch(error){
       case 'first error':
           return 'There is problem. First error.';
       case default:
           return 'There is unknown error.
   }
}
```
Or even it could be:
```ts
if (error) return error
```

Thank you

2022-09-08 09:01 UTC, MohammedJ18 commented on src/runtime/composables/useAppManager.ts
> +            if (error)console.log('حدث خطأ اثناء شراء الباقة')
I completed returning the specific error in `return`.
 You can check it.

2022-09-08 14:16 UTC, Gruce approved these changes
Hello @MohammedJ18 ,
I have approved the pull request, but in the future it needs more specific errors to be showed and controlled by the composables.

Thank you.

2022-09-08 14:16 UTC, merged