Usage of fetchPacks function
EnabApp/core pull request #30
Opened 2022-09-08 17:46 UTC by MohammedJ18

2022-09-08 19:18 UTC, Gruce commented on src/runtime/composables/useAppManager.ts
> +      this.packs = packs.map(pack => new Pack(pack))
You have used `Pack` model but you didn't imported it. You have to import it.

2022-09-08 20:06 UTC, Gruce commented on src/runtime/composables/useAppManager.ts
> +      this.packs = packs.map(pack => new Pack(pack))
You have selected `packs_apps(app_id)`. That is good, but you really need to select
```
*, packs_apps (
          id,
          app:app_id (
              *,
              users_apps(id),
              apps_services(
                  id, app_id, title, points, icon, description, users_services(id)
              )
          )
      )
```

And then you have to edit your `Pack Model` as the following comment.

2022-09-08 20:07 UTC, Gruce commented on src/runtime/models/Pack.ts
> +    this.apps = args.apps?.map(app => new App(app))
```
    this.apps = args?.packs_apps?.map(pack_app => new App(pack_app.app))
```

2022-09-08 20:09 UTC, Gruce requested changes
Hello @MohammedJ18 ,

I have reviewed your code and it needs some changes. I have provided you enough information and you can check the comments on the code above.

Thank you.

2022-09-09 16:38 UTC, MohammedJ18 commented
Hi @Gruce,
I completed the changes. You can check and let me know if there are errors or things that need to be added.
Thank you.

2022-09-09 18:49 UTC, merged